### ISSUE TITLE
Support order of certificate packs

### ISSUE THREAD

**Issue by vences** [terraform-providers/terraform-provider-cloudflare#576]
[Ordering Dedicated Certificate](https://api.cloudflare.com/#certificate-packs-order-certificate-pack) would be great to be  supported on the terraform provider.

Below the curl for ordering dedicated certificate with Custom Hostname:
```
curl -X POST "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/ssl/certificate_packs" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: c2547eb745079dac9320b638f5e225cf483cc5cfdda41" \
     -H "Content-Type: application/json" \
     --data '{
          "hosts":["example.com","www.example.com","foo.example.com"],
          "type":"dedicated_custom"
      }'
```

**Comment by jacobbednarz** [comment]
I've actually got a version of this that we use internally for managing our certificates but we've had *alot* of issues with requesting and managing dedicated certificates using the API and I haven't felt comfortable adding it to the public provider just yet.

**Comment by vences** [comment]
Thks Jacob for your quick answer. 
May I ask you which issues are you facing? Is anything planned to fix those issues and then roll out it in terraform?

**Comment by jacobbednarz** [comment]
We have two major issues. The first is that many of our domains are in the Alexa top 100 which results in triggering all sorts of alarms when we try and get new certificates. This has been fixed in the past by contacting support and _generally_ only happens the first or second time we use the domain. The second is that there isn’t a way to update a certificate in place (despite the documentation stating otherwise). This means that you always need to have N + 1 slots available on your account if you want to update without service interruption. Both of these have been raised with Cloudflare and are being looked at however I haven’t pursued it in a while. 

Until the latter issue is addressed, it’s not really worth using Terraform for the resource but would gladly add it if that was fixed.

**Comment by vences** [comment]
Thanks for your quick reply. For your second point in fact, it seems not even possible on the dashboard. The only way to generate a new cert is as you said order a new one and then delete the previous one. It seems align with the API: https://api.cloudflare.com/#certificate-packs-list-certificate-packs (List or Order a new one).
The DELETE seems not to be documented there but it is still the same schema
`DELETE zones/:zone_identifier/ssl/certificate_packs/:id_cert`

**Comment by jtcressy** [comment]
@jacobbednarz The latter issue of needing N+1 slots is something I also have to contend with right now, and also preventing service interruption. But this should be a supported pattern in terraform: If the SANs on a dedicated_custom_certificate_pack resource are immutable and you have `create_before_destroy` set in `lifecycle {}`, then the actions taken by terraform will be to order a new certificate with the new SAN list, then delete the old one after the new one is created.
It's still probably not 100% desirable since you still have to have that extra unused slot on your cf subscription, but this pattern should prevent service interruption.

+1 for having a tf resource for ordering these certs. it would be fantastic as I would then be able to automate adding new subject alternative names to our edge.
